### ISSUE TITLE
 sorasvl-server cannot be started

### ISSUE THREAD

**Issue by lijin2021** [YuqiHuai/SORA-SVL#1]
Hi!When I am running SVL Simulator without wise.svlsimulator.com, sorasvl-server does not start properly. I performed the following troubleshooting.
First query the currently running container via docker ps, sorasvl-server is not running.
After that, I created a new container with the image of sorasvl-server and entered the container and typed npm run start and got the following error:
![1](https://user-images.githubusercontent.com/49550077/171996513-4c7558f0-cde2-44bd-817f-cd4daf584937.png)
How should I fix this error.
Thanks!

**Comment by YuqiHuai** [comment]
Hi. Sorry for the late response!

The error says the database hasn't started, maybe there is something wrong with the sorasvl-mongo.

I made a mistake earlier last week for the .env file of the server directory

It should be 
```
MONGO_URL="mongodb://sorasvl-mongo:27017" 
MONGO_DB_NAME="WISE"
```
instead pf localhost:37017 (for the MONGO_URL)

**Comment by YuqiHuai** [comment]
Hi, hope my answer above has solved your issue! I added some details to the readme to make the setup process clearer.

I already see others raising issues after being able to set up the project, therefore I am going to assume this issue no longer exists.

Please open a new issue for other problems! Again thank you for raising problems like this!
