### ISSUE TITLE
 Images from local cloud cannot be loaded

### ISSUE THREAD

**Issue by DOMINICQQQ** [YuqiHuai/SORA-SVL#11]
I successfully built and deployed the docker container and the front end seems to be working well.
maybe something was wrong.
![1](https://user-images.githubusercontent.com/100404516/176642544-016d75ec-b26d-43e9-b383-afb29c4a60d0.png)

**Comment by KOREAN139** [comment]
Maybe this can be solved with proxy setting, i will make PR of this @YuqiHuai

**Comment by DOMINICQQQ** [comment]
@KOREAN139  These two errors are the main ones.
![2](https://user-images.githubusercontent.com/100404516/176671220-5a0fbc44-6680-4fdb-8a12-63dffacd1587.png)

**Comment by KOREAN139** [comment]
@DOMINICQQQ Did you download the assets from google drive as written in `README.md` ?

**Comment by DOMINICQQQ** [comment]
yes.
![Uploading 3.png…]()

**Comment by KOREAN139** [comment]
@DOMINICQQQ I just made a PR, can you check out the PR version and share the results?

**Comment by YuqiHuai** [comment]
Hi! Not sure why this would happen ... Don't think it is related to CORS because this didn't happen before and I've talked with a few others previously ...

Try to look at the following:
- Check if you can access http://localhost/api/v1/assets/download/preview/b819be12-5d1e-416b-8d19-609f54f50323
- Check if there are 6 files under server/assets/preview/maps/b819be12-5d1e-416b-8d19-609f54f50323

**Comment by DOMINICQQQ** [comment]
Hi！The first one my result is： Not found.
there are 6 files in `server/assets/preview/maps/b819be12-5d1e-416b-8d19-609f54f50323`
![4](https://user-images.githubusercontent.com/100404516/176846330-29b64a17-1d05-48a4-a69c-8b97f425ba8f.png)
And I also can't seem to launch via the Phthon API

**Comment by YuqiHuai** [comment]
Hi. It looks like things are set up correctly. I cannot figure out why this is happening to you. Something about the server is wrong, but then I cannot explain why the front end shows any data at all.

Can we schedule some time over the weekend to do a Zoom 1-on-1 meeting so I can look at your system and determine what is going on?

**Comment by DOMINICQQQ** [comment]
Hi, when are you free this weekend, we can see what's going on, if it's not a hassle for you.

**Comment by YuqiHuai** [comment]
Hi, sorry I guess it is too hard to schedule something like this over Github, I forgot to check this issue yesterday. Can we talk over email? My address is yhuai@uci.edu

**Comment by YuqiHuai** [comment]
To verify server container can access the asset files (maps, plugins, and previews), run
```
docker exec -it sorasvl-server /bin/bash
```
and verify `assets` directory exists and there are files under `assets`.

In this project, the assets directory is mounted to a location in the `server` container by line https://github.com/YuqiHuai/SORA-SVL/blob/4746da172345eb92aaa34a422205535bb7e93578/docker-compose.yml#L11

Some Docker permission issues prevented this mounting to be done thus causing `server` to return NotFound when trying to access assets and previews.

**Comment by YuqiHuai** [comment]
The issues was resolved. For some reason Docker could not mount directories in the Desktop directory, which caused the server container unable to access asset directory.
