### ISSUE TITLE
I followed the tutorial steps, but in step 5, build failed

### ISSUE THREAD

**Issue by CSU-Jing** [YuqiHuai/SORA-SVL#13]
I followed the tutorial steps, but in step 5, build failed.And What does the fourth step mean？
Template not found in folder.
thanks.

**Comment by YuqiHuai** [comment]
Hi, I haven't seen this kind of error before. Can you attach some screenshots?

Step 4 means you should create a file named ".env" in the server and client directories, following the examples named ".env.template"

**Comment by CSU-Jing** [comment]
![2022-07-10 15-21-12屏幕截图](https://user-images.githubusercontent.com/108818201/178135293-623a2b30-1b89-4c82-a6fb-88e4fb225518.png)
I have tried many times, and now build is successful, but the page is still blank

**Comment by CSU-Jing** [comment]
I checked the source code of the web page, which says 'You need to enable JavaScript to run this app.'

**Comment by YuqiHuai** [comment]
Hi,
Based on the screenshot this is caused by either the server not running or the database not running.
Can you run `docker ps -a` to check which containers are up?

**Comment by YuqiHuai** [comment]
Hi! Sorry for the late response. I tried reaching out to you via Email already. Please make sure to check your inbox!
