### ISSUE TITLE
Cannot open http://localhost

### ISSUE THREAD

**Issue by sixiaixixiya** [YuqiHuai/SORA-SVL#17]
I cannot open http://localhost after I built this project by "docker-compose up --build -d". The web shows "This site can't be reached". Is anybody here meet the same question? I really need your help!

**Comment by YuqiHuai** [comment]
Hi. I have been quite busy in recent weeks so I cannot thoroughly look into what is going on for you. Make sure to have correct `.env` files in both server and client.

**Comment by sixiaixixiya** [comment]
Hi. I cannot understand those tips from the Readme. 
"
> UPDATE 2022-06-30: WISE provides geojson for some of the maps. To access those geojson, download `geojson.json` from Google Drive, and then import them into MongoDB.

4. Create `.env` file for server and client following the template (should be same as template, change if you know what you are doing) (The template refers to `server/.env.template` and `client/.env.template`)
"
Can you teach me how to  import `geojson.json` into MongoDB?
Where are server/.env.template` and`client/.env.template`? I do not find them in SORACode.
Sincerely appreciate your help！

**Comment by sixiaixixiya** [comment]
Hi thanks for your help. I finally run the quick_start python script by sora-svl! And it works with Apollo7.0.
But I really wanna to know why Api-Only mode needs pressing the ON button in sora-svl? 
And python-api sim.run() is not work.
Sincerely thank you for your help again!
![图片](https://user-images.githubusercontent.com/104459086/185964518-793a3507-8a14-4956-8edc-a6678d4e47dc.png)

**Comment by YuqiHuai** [comment]
Hi, I tried to mimic the original WISE svl cloud as much as possible, and this is how it used to work.

In your python script you can send an http request to the local cloud to trigger api only mode, the sim.run().

**Comment by sixiaixixiya** [comment]
Ok I got your idea. But I have a new issue now.
I encountered a problem when I want to use Visual Editor. It is no-maps here!
This is a so tough question for me. Looking forward to your reply sincerely.
![图片](https://user-images.githubusercontent.com/104459086/186081036-4fe5815c-b6d2-48cd-b2b3-09350719be84.png)

**Comment by YuqiHuai** [comment]
Hi, I haven't used visual editor, and the goal of this project is to just support API only simulations.

**Comment by sixiaixixiya** [comment]
I wanna to test the planning module of Apollo7.0 by sora-svl. How can I created the scenarios which I designed for test planning? It is too difficult to set obstacles only by python api without json files saved by VSE.

**Comment by YuqiHuai** [comment]
I see. That is a feature I didn't know about. I only knew about NPC obstacles https://github.com/lgsvl/PythonAPI/blob/master/quickstart/13-npc-follow-waypoints.py

Unfortunately I would not be implementing more to support these. I am also a full time student so I was hoping the open source community can work together to get all the features supported.

**Comment by sixiaixixiya** [comment]
Wahoo! I think you has already done a good job yet. Thanks for your contribution! Let's make the project better together.

**Comment by YuqiHuai** [comment]
Thanks for the feedback as well!

**Comment by sixiaixixiya** [comment]
Hi Bro. I find a new question about MonoBleedingEdge's libmonobdwgc-2.0.so. I want to run LGSVL simulator by remote desktop of RDP connect. And I found the question is that LGSVL-simulator can be running in my server host Ubuntu but can not be started by Xrdp  Remote Desktop. And I use gdb ./simulator to catch errors which shows that the libmonobdwgc-2.0.so may have some problems to be imported. Needless to say, I really need your help! Thanks.
![gdb](https://user-images.githubusercontent.com/104459086/186615209-6f699d5b-47f0-4563-abbe-fdb485b30d97.png)

**Comment by YuqiHuai** [comment]
@sixiaixixiya Hi sorry I just got my own stuff done and I am coming back to try to answer questions. I am not familiar with the setup you are using (remote desktop, XRDP, etc.) therefore I might not be able to help with this.

**Comment by sixiaixixiya** [comment]
That's OK! Never mind. But I have one more question now. I want change the http://localhost of SORA wise to avoid url address conflicts with my local Gitlab. I try to change the port 80 of nginx to 81 and change the .env of client to  http://localhost:81. I cannot use it normally though it  can be compiled successfully. Also I just find the container of your 4 database will be stopped when I open my url http://localhost:81. 
In a word. I wish you can teach me how to change the url and the port 80of database container sincerely!

**Comment by YuqiHuai** [comment]
I haven’t tried changing ports but I believe all you have to change is actually this line

https://github.com/YuqiHuai/SORA-SVL/blob/49d3d068f35069ecec438d149d45c272b4316261/docker-compose.yml#L34

change it to 81:80 and see if it works?

**Comment by sixiaixixiya** [comment]
Thanks! I did it.
change docker-compose.yml --- 81:81
change .env of client ---localhost:81
change nginx.cofig --- listen:81
do not change mogon/setup import.sh!
now I can open url: localhost:81 it work well!

**Comment by YuqiHuai** [comment]
Sounds good! Well I’m glad it is working! But I meant you probably could get it working by just changing that one line to 81:80, not 81:81.

You changed a few more places that were meant for communication between containers. But you got really lucky and got everything working!
