### ISSUE TITLE
How to run a simulation?

### ISSUE THREAD

**Issue by Creling** [YuqiHuai/SORA-SVL#18]
Hi,

I deploy this project successfully, but I dont know how to run a simulation. I mean, a simulation with a map, a vehicle and other setting just like what we run on WISE. Could you give some advice? The Simulations page is a bit confusing:

![image](https://user-images.githubusercontent.com/43109504/184596044-3143804a-c710-4a54-956d-6aed063a10a3.png)

Creling

**Comment by YuqiHuai** [comment]
Sorry for the confusion. I do plan to make this better in the future.
