### ISSUE TITLE
Mongo error and .env files

### ISSUE THREAD

**Issue by rogeherlor** [YuqiHuai/SORA-SVL#2]
Hello! I am also trying to use the SVL simulator API but I can't start the server container like #1 

When I access http://localhost:27017/ it appears: 'It looks like you are trying to access MongoDB over HTTP on the native driver port.'

In 'https://stackoverflow.com/questions/23446876/cannot-access-mongodb-through-browser-it-looks-like-you-are-trying-to-access-m' they say there is no HTTP access at the default port of 27017. 

Also could you tell me where can I find '4.Create .env file for server and client following the template (should be same as template, change if you know what you are doing)' templates?

Ty!

**Comment by YuqiHuai** [comment]
Hi!
You should not be able to access http://localhost:27017/.
Only the server container can access MongoDB at sorasvl-mongo:27017
This is done through Docker network https://github.com/YuqiHuai/SORA-SVL/blob/125c5c985f75a600b6e22d5374a4b1c8529df0c8/docker-compose.yml#L46
===
The templates for the .env files are in the server and client directory named ".env.template".
You can basically rename it to .env and things should be working appropriately.

**Comment by rogeherlor** [comment]
I tried to access it that way because I didn't know the way to do it :)
Just following step 4 and renaming those to .env works, ty!

Now I can communicate with your local server and start the API.
![image](https://user-images.githubusercontent.com/8066907/172585766-44d92f60-4635-4b27-b553-72c3d5e2b716.png)

But when I run the python API and try to load a map (I tried some of them) it appears for example: SingleLaneRoad 0% and then this error
![image](https://user-images.githubusercontent.com/8066907/172584889-96086411-5379-4555-a077-ed597d49f938.png)

It is the script remote.py from the python API. Do you know why this could happen?
![image](https://user-images.githubusercontent.com/8066907/172586632-441347f6-b182-4850-81f1-99fa588a4e0f.png)

**Comment by rogeherlor** [comment]
I tried to access like that because I didn't know how to do it :)
I renamed the files and it is working

Amazing work!
