### ISSUE TITLE
How 2 get assets by wise?

### ISSUE THREAD

**Issue by anl12** [YuqiHuai/SORA-SVL#21]
Hi yuhuaiqi , Wise is not stable in last week, so i find this Project.This project is useful in offline status.
i have a question now,  How did you get the svl assets, . i want get some svl assets by myself.
your save svl assets in 2022.6, Maybe you can update the svl assets again.
Best Regards.

**Comment by YuqiHuai** [comment]
Hi! To download assets from wise you would use their APIs. You can take a look at my server source code, the download endpoint is exactly the same on the official WISE server.

**Comment by anl12** [comment]
I don't believe any of the official assets got updated right?
->i find this map, it update later than you download svl assets. so i have this question.
https://wise.svlsimulator.com/maps/profile/a5b1391c-f8f5-4a6d-8e84-30dafd0617ea
any way thanks you answer. i will 2 see your server source code .

**Comment by YuqiHuai** [comment]
I see. Thanks! The download looks like this 
https://github.com/YuqiHuai/SORA-SVL/blob/022c9e4b1db548a19734d4dfcc76c868f5051886/server/src/routers/assets.router.ts#L8

**Comment by YuqiHuai** [comment]
You get its assetGuid like this:
https://wise.svlsimulator.com/api/v1/maps/a5b1391c-f8f5-4a6d-8e84-30dafd0617ea

Then download it at:
https://wise.svlsimulator.com/api/v1/assets/download/bundle/a20b0720-709b-4e5e-af8b-3749d19e328b

**Comment by anl12** [comment]
thanks
