### ISSUE TITLE
VSE Error Failed to load map. Exception: assetGuid must not be null when trying to get $Environment asset.

### ISSUE THREAD

**Issue by umdreamer** [YuqiHuai/SORA-SVL#25]
When I used the VSE in the local version. It got the following errors in loading maps.
````
Failed to load map . Exception: assetGuid must not be null when trying to get $Environment asset.
Assertion failure. Value was Null
````
`http://localhost/api/v1/assets/download/bundle/` is none, as it should be 
`http://localhost/api/v1/assets/download/bundle/74e497d2-aa6a-447b-a24a-373e43116771`

**Comment by umdreamer** [comment]
When I dig into the code in stepwise debugging, I found the http://localhost/api/v1/maps?display=sim&limit=50&offset=0, this website has not assetGuid property. The values are as the following:
```
{
            "isShared": false,
            "isFavored": true,
            "isOwned": false,
            "accessInfo": {
                "userAccessType": "favored",
                "owner": {
                    "id": "0d888b00-fa53-47c1-882a-b68391268a11",
                    "firstName": "SVL",
                    "lastName": "Content"
                }
            },
            "supportedSimulatorVersions": [
                "!x-debug-map"
            ],
            "id": "a6e2d149-6a18-4b83-9029-4411d7b2e69a",
            "name": "SingleLaneRoad",
            "description": "This map is a simple two-way single-lane road used for basic test cases. This is a convenient map for running basic scenarios for your autonomous driving system modules.",
            "copyright": "LG Electronics Inc.",
            "licenseName": "LG Content",
            "ownerId": "0d888b00-fa53-47c1-882a-b68391268a11",
            "accessType": "public",
            "imageUrl": "/api/v1/assets/download/preview/b819be12-5d1e-416b-8d19-609f54f50323",
            "hdmaps": "apollo30,apollo50,autoware,lanelet2,opendrive",
            "status": "active",
            "owner": {
                "id": "0d888b00-fa53-47c1-882a-b68391268a11",
                "firstName": "SVL",
                "lastName": "Content"
            },
            "shareRequests": []
        },
```
We can see the `b819be12-5d1e-416b-8d19-609f54f50323` should be the assetGuid, but it doesn't have a key called `assetGuid`.

In the 
```
public async Task Initialize()
        {
            if (IsInitialized)
                return;
            var library = await ConnectionManager.API.GetLibrary<MapDetailData>();

            var assetService = new AssetService();
            var mapsInDatabase = assetService.List(BundleConfig.BundleTypes.Environment);
            var cachedMaps = mapsInDatabase as AssetModel[] ?? mapsInDatabase.ToArray();

            foreach (var mapDetailData in library)
            {
                var newMap = new MapMetaData(mapDetailData.Id, mapDetailData.Name, mapDetailData.AssetGuid)
                {
                    assetModel = cachedMaps.FirstOrDefault(cachedMap => cachedMap.AssetGuid == mapDetailData.AssetGuid)
                };
                AvailableMaps.Add(newMap);  
            }

            IsInitialized = true;
            Debug.Log($"{GetType().Name} scenario editor extension has been initialized.");
        }
```
The mapDetailData's value is a map's json string values. It has not AssetGuid, so the initialization can not find the map.

This may be a bug in the current implementation.

**Comment by YuqiHuai** [comment]
Hi, thanks for reporting the issue.
Indeed, assetGuid is needed for any asset. I am not too familiar with VSE.
Are you saying, assetGuid is missing for a specific map that I collected?

**Comment by umdreamer** [comment]
After digging into the Simulator code, I found that for VSE, the local server cannot provide the correct json result. Wheereas the wise can give the result which contains assetGuid. See the following image:
![image](https://user-images.githubusercontent.com/15782682/208112442-b3395a4f-f491-49e6-a6d9-b12d1e365a04.png)

If we directly use the url to get the results, both the http://localhost/api/v1/maps?display=sim&limit=50&offset=0, and https://wise.svlsimulator.com/api/v1/maps?display=sim&limit=50&offset=0, give the same results.

This implies that the WISE server adds the assetGuid after the URL result. The returned json comes from the mongo/global.json. The local server just returns the original global.json string, while the WISE adds more than global.json.

I think the solution is to modify the code in server/src/routers/api.router.ts to reflect the assetGuid. I'll have a try.

**Comment by YuqiHuai** [comment]
Hi, thanks for finding this out. From my understanding `assetGuid` should be in the database, but currently looks like it is not there, and you are proposing to modify `api.router.ts` to add `assetGuid` even if the database json file does not include it. Is my understanding still correct?

**Comment by umdreamer** [comment]
@YuqiHuai Yes, you are correct. I am now learning for Node.js and React to modify the code. I'll give the feedback once I work out.

**Comment by YuqiHuai** [comment]
Hey, how did it go? I think I will have some time after Feb 2 deadline and I can definitel try to get this fixed.

**Comment by umdreamer** [comment]
> Hey, how did it go? I think I will have some time after Feb 2 deadline and I can definitel try to get this fixed.

Hi @YuqiHuai , I'm working on it. I have found the solution to add the map code. Now the VSE can load maps correctly. I'll also add the vehicle method. I'll create a Pull Request when I finish in this week.:)

**Comment by YuqiHuai** [comment]
Sounds super good. Thank you so much for helping!

**Comment by umdreamer** [comment]
@YuqiHuai I just pulled a PR #28  for these functions. You can have a look if it can be merged into master. Thanks.

**Comment by umdreamer** [comment]
The PR #29  implementing these functions has merged into master.

**Comment by YuqiHuai** [comment]
Thanks @umdreamer for the contribution in PR #29 
Closing this issue for now.
