### ISSUE TITLE
ERROR [sora-svl_server 7/7] RUN ["npm", "run", "build"]  

### ISSUE THREAD

**Issue by s0966066980** [YuqiHuai/SORA-SVL#26]
![2023-01-04 19-38-19 的螢幕擷圖](https://user-images.githubusercontent.com/45198905/210547325-b1e4022a-71e7-4558-9a18-c94325f9830e.png)

how can i fix this problem

**Comment by hustwyk** [comment]
> ![2023-01-04 19-38-19 的螢幕擷圖](https://user-images.githubusercontent.com/45198905/210547325-b1e4022a-71e7-4558-9a18-c94325f9830e.png)
> 
> how can i fix this problem

Hi there, I met the same problem as the pic shows, may I consult how to deal with it. Thanks a lot~
