### ISSUE TITLE
docker compose up failed: TS2403

### ISSUE THREAD

**Issue by yaoweixiao-ux** [YuqiHuai/SORA-SVL#31]
![8d5bbee91d368d29cd847357fa6da66](https://user-images.githubusercontent.com/71545947/217215084-57cc1e27-818c-41a6-8f23-b5bd221dc70b.png)

**Comment by YuqiHuai** [comment]
Hi, thanks for posting an issue. I have not seen this issue before, can you provide a little more context, for example, what command did you run?

**Comment by yaoweixiao-ux** [comment]
sudo docker-compose up

**Comment by YuqiHuai** [comment]
Looks like something is wrong with @types/node. Will investigate soon.

**Comment by umdreamer** [comment]
May you have to use node.js 18 instead of 17 in original version.

**Comment by YuqiHuai** [comment]
@yaoweixiao-ux 
After a closer inspection, the Dockerfile already states using `node:18` https://github.com/YuqiHuai/SORA-SVL/blob/3bd5ff0e2c1a0cb5845f66cbf48750a41bb37398/server/Dockerfile#L1
With a fresh download of the repository, I ran `cp server/.env.template server/.env && cp client/.env.template client/.env`, then `docker compose up -d`. All containers are built and running without any problems.

**Comment by YuqiHuai** [comment]
@yaoweixiao-ux have you resolved the issue?

**Comment by yaoweixiao-ux** [comment]
thank you I so==solved this issue

**Comment by YuqiHuai** [comment]
Sounds good. Thank you for the info. @yaoweixiao-ux
