### ISSUE TITLE
About original LGSVL API doc 

### ISSUE THREAD

**Issue by GiantSeaweed** [YuqiHuai/SORA-SVL#32]
Really great work! Thank you for the huge contribution!

Recently I found I could not even visit the lgsvl api doc https://www.svlsimulator.com/docs/python-api/. (Can anyone still have access to it?)

I was wondering whether we can also save a copy a documentation (for svl and dreamview) as well. 

Although we can learn svl from quickstart code example, beginners do not know much about dreamview's api.

**Comment by GiantSeaweed** [comment]
Thank you for the archive pointer!

**Comment by GiantSeaweed** [comment]
Thank you for the archive pointer!

**Comment by yaoweixiao-ux** [comment]
@YuqiHuai I have collect some LGSVL origin doces, if you wan remake documentation, I can give you!
I think we should make a conversition tube for us to do this greate job

**Comment by YuqiHuai** [comment]
@yaoweixiao-ux Sounds good. I just created a Slack workspace for us to communicate. We cannot rely on using issues to communicate.

https://join.slack.com/t/uci-tbg3282/shared_invite/zt-1ovwoq5f9-qO~Tv07irNmug7KkoYu46A

**Comment by umdreamer** [comment]
Is it possible to make the original documentation to located in the makedocs so that more people can access it? And we can make these *.md files in this repo for the documentation, and the built docs to readthedocs.org.

**Comment by YuqiHuai** [comment]
@umdreamer I’m also thinking about this. My plan is to add a docs directory and build the documentation source file there. What are the MD files you are referring to? I thought the original documentation was built with Sphinx so the source would be .rst files.

**Comment by YuqiHuai** [comment]
@GiantSeaweed @umdreamer I have started our own documentation in the `docs` directory. I have also temporarily hosted a compiled version at https://www.ics.uci.edu/~yhuai/SORA-SVL/

I am not sure if there is a better way to convert HTML back to Sphinx source code, but I have manually created the ones I committed here https://github.com/YuqiHuai/SORA-SVL/commits/main

**Comment by GiantSeaweed** [comment]
Wow it's fantastic. I am not very aware of fully-automated html2rst tools, but your manual creation looks the same as original ones!

**Comment by YuqiHuai** [comment]
Thanks for your feedback! I will try to incorporate some more documentation when I have time. 
I have added the task to future plans and I am going to close this issue and work on other issues.
