### ISSUE TITLE
Adding Custom Map and ROS2 Autopilot 

### ISSUE THREAD

**Issue by abustaoglu** [YuqiHuai/SORA-SVL#39]
Hi, i was working with the custom private map and ros2 autopilot on lgsvl online mode, not autoware or apollo. I have two question about this.

1. My map folder look like this and i don't now how can import.

![ss](https://user-images.githubusercontent.com/72972819/220932345-c338aaec-015e-4197-a97f-0558991e1447.png)

2. How can i create connection between localhost and ros? Do i need to write api or modifying lgsvl_bridge[[link](https://github.com/lgsvl/ros2-lgsvl-bridge)] will be enough?

**Comment by YuqiHuai** [comment]
Hi @abustaoglu thanks for posting the issue. I am most familiar with running SVL with Baidu Apollo, therefore I might not be able to give you the most accurate information. I am also currently away therefore I might not be able to respond as soon as I could.

1. To add a map, you need to modify `mongo/setup/maps.json`: add an entry that includes `cid`, `id`, and `data.assetGuid`. The server uses `cid`/`id` (they are the same) to identify the asset mapped to this file, and sends the asset to SVL client.

2. Creation between localhost and ROS should be handled by the bridge you mentioned, and I believe it is a plugin that I have downloaded and saved. As long as you have a vehicle configured to use that bridge it should all just work out.

**Comment by abustaoglu** [comment]
Hi @YuqiHuai. Thanks for advices.. With manually adding entrys to [maps.json, hd_maps.json, global.json], i have successfully added my map to local cloud but i dont see my map here [(http://localhost/maps)]. I can call the map using python api, but I cannot view it on the server. what would be the reason?

**Comment by YuqiHuai** [comment]
@abustaoglu 
I forgot to mention this script https://github.com/YuqiHuai/SORA-SVL/blob/6192e6dc32fca2e162310ba4e5e7e259f23c5a3b/toolset/map_generator.py

the maps webpage looks at the global collection to display all maps, and the download endpoint looks at the maps collection to provide the download url. To make it show up on the maps webpage, you also need to insert the object to global collection.

**Comment by abustaoglu** [comment]
you mean geojson.json file?

**Comment by YuqiHuai** [comment]
This one https://github.com/YuqiHuai/SORA-SVL/blob/6192e6dc32fca2e162310ba4e5e7e259f23c5a3b/mongo/setup/global.json

you should be able to see this collection named global in the database.

**Comment by abustaoglu** [comment]
i have modified global.json file but webpage appearance doesn't change. maybe i need to find a way to use map_generator.py script.

**Comment by abustaoglu** [comment]
Hello @YuqiHuai, i have connected local host and ros2 lgsvl bridge. here is the steps:

1.  Build ros2 bridge according to [this](https://race.ossdc.org/docs/system-under-test/ros2-bridge/) link.
2.  Run [this](quickstart/22-connecting-bridge.py) after changing bridge and sim port(3000/8181).
3.  Run lgsvl_bridge from terminal.

**Comment by YuqiHuai** [comment]
@abustaoglu  Sounds good!
and by the looks, SVL hasn't sunsetted their documentation, just the cloud
https://www.svlsimulator.com/docs/

**Comment by rensixu** [comment]
Hello @YuqiHuai  Where is the simulator's exe. I could not found that in the project?

**Comment by rensixu** [comment]
> @rensixu `simulator.exe` is not part of this project. It is just where you installed the SVL simulator, did you mean to post this comment in #41?
Hi @YuqiHuai  Thankyou very much for your reply. I reference that ticket, and try to change the config.yaml file in my SVL installed folder. It try to link "http://localhost/", but then have error like this.
![Screenshot 2023-03-05 21:37:51](https://user-images.githubusercontent.com/63765273/222963901-83dbea6e-c15f-4a5f-9049-0529e8ba3a64.png)
This is my output when I run "docker compose up --build -d", it seems ok ,right?
Should this cmd be executed every time when use the lgsvl simlutor?
![Screenshot from 2023-03-05 21-39-47](https://user-images.githubusercontent.com/63765273/222963973-5971c648-489b-4d81-9c38-e767a52752c7.png)

**Comment by YuqiHuai** [comment]
@rensixu 

1. I haven't seen any error like this. Please show a screenshot of the root directory of the simulator and a screenshot of the content of `config.yml`
2. The output of `docker compose` looks good. You just have to start the server then it serves as the original WISE cloud, so you do not need to rerun this everytime you run the simulator. You only run the `dock compose` command if the containers have exited.

**Comment by rensixu** [comment]
![a](https://user-images.githubusercontent.com/63765273/223114096-adb12006-afdf-4d1b-9434-7f5be492119d.png)
![b](https://user-images.githubusercontent.com/63765273/223114106-3121151a-d2df-40d8-9260-97d683839c1e.png)
@YuqiHuai  pls reference

**Comment by YuqiHuai** [comment]
@rensixu 
These all look correct. Are you able to see all the contents from `http://localhost`?

**Comment by rensixu** [comment]
![image](https://user-images.githubusercontent.com/63765273/223420094-53729b8c-1b8d-430f-8b90-c627f4942f53.png)
@YuqiHuai 
yes, like this, but only the contents

**Comment by YuqiHuai** [comment]
@rensixu this indeed looks like a new problem. Can you open a new issue so I can properly track and try to resolve the issue?

**Comment by abustaoglu** [comment]
see #43

**Comment by abustaoglu** [comment]
Hello @ABCRepository, you can the related link [here](https://www.svlsimulator.com/docs/system-under-test/ros2-bridge/)
