### ISSUE TITLE
Connection problems between SVL simulator and localhost

### ISSUE THREAD

**Issue by AlexandrZabolotny** [YuqiHuai/SORA-SVL#41]
Hi evryone!
I have 2 questions. Maybe somebody could help me!

1.
I have done 1-6 steps of given instruction! All OK!
By the way then I open http://localhost/simulations **I see empty page**
![Screenshot from 2023-03-01 12-04-05](https://user-images.githubusercontent.com/61351599/222093523-1441c959-c3e6-4df6-bc68-380acdb6998e.png)
**Is it OK?**

2.
I have done 7th step.
![Screenshot from 2023-03-01 11-54-51](https://user-images.githubusercontent.com/61351599/222094779-64a33954-1a47-478f-9b30-8871ea573e97.png)
My config file consists
_headless: false
read_only: false
api_hostname: "localhost"
api_port: 8181
cloud_url: "http://localhost"_

And now I run SVL simulator.
It continues to connect to wise.svlsimulator.com
**Why? How I can solve it?**
![Screenshot from 2023-03-01 11-53-06](https://user-images.githubusercontent.com/61351599/222095756-084bf0a2-d078-47f9-9b18-2480651cc5b3.png)

**Comment by abustaoglu** [comment]
Hello @AlexandrZabolotny, can you share the parent folder's screenshot. Because i run my sim from different location. Maybe you edited wrong config file.

**Comment by AlexandrZabolotny** [comment]
> Hello @AlexandrZabolotny, can you share the parent folder's screenshot. Because i run my sim from different location. Maybe you edited wrong config file.
![Screenshot from 2023-03-01 16-42-04](https://user-images.githubusercontent.com/61351599/222155733-01460f0e-dbea-4a79-bcfb-f24238d93784.png)

**Comment by AlexandrZabolotny** [comment]
> Hello @AlexandrZabolotny, can you share the parent folder's screenshot. Because i run my sim from different location. Maybe you edited wrong config file.

Could you send your screenshot and config?
I will follow your example

**Comment by abustaoglu** [comment]
I think you need the build svl like [this](https://race.ossdc.org/docs/installation-guide/installing-simulator/) link. My folder structure look like this, config file is also same as like you.

![Screenshot 2023-03-01 165258](https://user-images.githubusercontent.com/72972819/222159303-18585694-39a1-49aa-84a6-e0bdf682fe01.png)

**Comment by AlexandrZabolotny** [comment]
My mistake was wrong locationg config file.

**Comment by lily410** [comment]
> Hi evryone! I have 2 questions. Maybe somebody could help me!
> 
> 
> I have done 1-6 steps of given instruction! All OK! By the way then I open http://localhost/simulations **I see empty page** ![Screenshot from 2023-03-01 12-04-05](https://user-images.githubusercontent.com/61351599/222093523-1441c959-c3e6-4df6-bc68-380acdb6998e.png) **Is it OK?**
> 
> 
> I have done 7th step. ![Screenshot from 2023-03-01 11-54-51](https://user-images.githubusercontent.com/61351599/222094779-64a33954-1a47-478f-9b30-8871ea573e97.png) My config file consists _headless: false read_only: false api_hostname: "localhost" api_port: 8181 cloud_url: "http://localhost"_
> 
> And now I run SVL simulator. It continues to connect to wise.svlsimulator.com **Why? How I can solve it?** ![Screenshot from 2023-03-01 11-53-06](https://user-images.githubusercontent.com/61351599/222095756-084bf0a2-d078-47f9-9b18-2480651cc5b3.png)

What is the file in the second picture？Is anything else need to be load besides the steps in readme？😶‍🌫️

**Comment by YuqiHuai** [comment]
@lily410 how did you launch SVL? The config file need to be right next to that executable.

**Comment by AlexandrZabolotny** [comment]
> 
> What is the file in the second picture？Is anything else need to be load besides the steps in readme？face_in_clouds @AlexandrZabolotny

It is step 7 of instruction

**Comment by lily410** [comment]
> 

Oh i see. Thanks for your reply!
