### ISSUE TITLE
Get stuck in step5

### ISSUE THREAD

**Issue by ideasplus** [YuqiHuai/SORA-SVL#42]
Hi, I recently try to run SVL simulator using this project. However, I met a strange issue in step5. I looked through all the issues and couldn't find a solution. 

After I run `docker-compose up --build -d`, everything look well.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/24294571/222664950-5b79074c-468d-4a0a-bf4d-2a2dd61fc8ad.png">
However, When I open localhost in browser, there is empty.
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/24294571/222665425-1c0abd8e-2b1d-48f0-9190-afc7731bb75a.png">
Then `I run docker ps -a`, I find **sorasvl-mongo** is exited. 
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/24294571/222665867-e3a663c1-15ee-4024-9e88-b57de3ffe34c.png">
After a while, **sorasvl-server** is also exited.
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/24294571/222666776-16f5650f-e3de-4f0b-ae17-93e47e9244b0.png">
Finally, I run `docker-compose up --build`, I get the error information.
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/24294571/222667371-6476ab79-2a1b-4832-b143-d226e1f9050c.png">
I really don't know how to solve this issue and get stuck for a few days. Could anyone provide some help? 

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Version of SVL [2021.03]

**Comment by YuqiHuai** [comment]
Hi @ideasplus 
Looks like the `mongo` container somehow failed to start, I suggest you try
```
docker compose up --build mongo
```
and focus on finding out what is wrong with this container. The server container requires the mongo container to start first.

**Comment by ideasplus** [comment]
@YuqiHuai Thanks for your reply!

After I run `docker compose up --build mongo`, the error info is same as above. I have not found how to solve the error code with 51 so far.
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/24294571/222869384-74af070e-41f0-4137-86fc-8257a081de03.png">

Another useful information. When I try to use `docker run -it  -p 28018:27017  -d sora-svl_mongo  bash` to start sora-svl_mongo, it looks well.
<img width="963" alt="image" src="https://user-images.githubusercontent.com/24294571/222869649-05ef4c58-23e7-4e33-9861-5567b59eb5fd.png">
However, when I use `MongoDB Compass` to access mongo, the error occurs.
<img width="595" alt="image" src="https://user-images.githubusercontent.com/24294571/222869799-5bcb29b1-23d4-4d28-ab41-7642218eb328.png">

Moreover, when I enter the container and try to import the data manually using sh `import.sh`, the error occurs again.
<img width="899" alt="image" src="https://user-images.githubusercontent.com/24294571/222869506-2d5a7229-6e99-4355-8ffa-5e9f8b6d3b00.png">

The most helpless thing is that I can successfully run the step5 on my laptop (Mac). But I really need to run SVL simulator for further experiments. I have to make it work on my workstation.
<img width="1529" alt="image" src="https://user-images.githubusercontent.com/24294571/222870161-cd373a99-f2f4-474a-91f2-262cacafc720.png">


I haven't seen these errors in other issues, nor can I find similar questions online. Really hope for some suggestions and help!

**Comment by YuqiHuai** [comment]
@ideasplus Thanks for the details.

You are able to get everything up and running on your Mac, but somehow unable to get the mongo container running on Ubuntu, is this correct?

This leaves me wondering, aren't docker images supposed to work on any platform? For example, I initially developed everything on Windows, then tested SVL + SORA SVL + Baidu Apollo on a Ubuntu machine. 

Can this be a docker problem? What version of docker are you running on Ubuntu?

**Comment by ideasplus** [comment]
@YuqiHuai Thanks for your quick feedback!

Yes, I can run SORA SVL well in my Macbook, and cannot in my workstation with Ubuntu system.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/24294571/222871670-a9447780-4e6b-4b3a-b6c5-67b87b08165b.png">

The docker version is `Docker version 20.10.2, build 2291f61` in Ubuntu system.

**Comment by YuqiHuai** [comment]
@ideasplus 
I checked my Ubuntu system and I am running Docker 23.0.0.

Can you try upgrading (reinstalling) docker on your Ubuntu machine?

**Comment by ideasplus** [comment]
@YuqiHuai Thanks for you info and I will try to upgrade docker now.

**Comment by ideasplus** [comment]
@YuqiHuai It's amazing! I pass the step5 via upgrading the docker version. Thank you so much!

Next I will try to import the self-defined map and vehicle config to SORA SVL and test SVL + SORA SVL + Baidu Apollo. Any errors will be reported in a new issue.

**Comment by YuqiHuai** [comment]
@ideasplus sounds good.
There were some other issues that have been closed with regard to adding vehicle and map. 
Many others have contributed scripts like:
- https://github.com/YuqiHuai/SORA-SVL/blob/main/toolset/map_generator.py
- https://github.com/YuqiHuai/SORA-SVL/blob/main/toolset/config_generator.py
These might be helpful for you.

**Comment by ideasplus** [comment]
@YuqiHuai 
Thank you very much for your generous help! Looking forward to your future research work.

**Comment by nanali0126** [comment]
@YuqiHuai， Hi I have met the same problem. I am using Windows right now, and the docker version is 23.0.5. May you tell me your Docker system in Windows system. thx!
