### ISSUE TITLE
Problem with Map Generator

### ISSUE THREAD

**Issue by abustaoglu** [YuqiHuai/SORA-SVL#48]
Hello everyone, 

Does anyone has successfully uploaded(from bundle) own map with script under toolset/map_generator.py? When use the script, server has been updated but i'm not able to load the map with python api so i can not view it on svl. All maps are load correctly except mine's. 

I would be grateful for any suggestions.

**Comment by YuqiHuai** [comment]
Hi @abustaoglu , thanks for posting the issue.

I believe the script should successfully update the database, and when the SVL client is requesting that resource, make sure the asset is in the server's asset folder.

Essentially the server provides a mapping between map id and the actual asset GUID. When the client requests a specific map id, the server first checks the database to locate the asset GUID, then sends that asset to the SVL client.
