### ISSUE TITLE
sorasvl-server error: TypeError: Cannot read properties of undefined (reading 'startsWith') ... at connectToDatabase (/workdir/dist/services/database.service.js:39:12)

### ISSUE THREAD

**Issue by jimaldon** [YuqiHuai/SORA-SVL#5]
docker logs `sorasvl-server` gives me the following error when trying to debug why every container but `sorasvl-server` is up and running. I'm using the standard `.env` file like in the template

```
> server@1.0.0 start
> node dist/index.js

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at connectionStringHasValidScheme (/workdir/node_modules/mongodb-connection-string-url/lib/index.js:9:30)
    at new ConnectionString (/workdir/node_modules/mongodb-connection-string-url/lib/index.js:85:34)
    at parseOptions (/workdir/node_modules/mongodb/lib/connection_string.js:209:17)
    at new MongoClient (/workdir/node_modules/mongodb/lib/mongo_client.js:62:63)
    at /workdir/dist/services/database.service.js:40:24
    at Generator.next (<anonymous>)
    at /workdir/dist/services/database.service.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/workdir/dist/services/database.service.js:27:12)
    at connectToDatabase (/workdir/dist/services/database.service.js:39:12)

```

**Comment by YuqiHuai** [comment]
Hi,
This issue is caused by the server container being unable to connect to the MongoDB container.

Can you attach your .env file here so I can check?

**Comment by jimaldon** [comment]
`server/.env`

```
MONGO_URL="mongodb://sorasvl-mongo:27017"
MONGO_DB_NAME="WISE"

```

**Comment by YuqiHuai** [comment]
This looks correct. I am not sure where the problem can happen. Still looks like a connection issue.

Can you take a look if you can access the mongodb url using Mongo Compass (desktop application), mongo url "mongodb://localhost:27017"

**Comment by YuqiHuai** [comment]
I just did some searching it is also possible that you put the ".env" file at the wrong location.
https://www.mongodb.com/community/forums/t/typeerror-cannot-read-property-startswith-of-undefined/146999/4
server/
├── src/ (… ,db.js , index.js)
├── .env
└── package.json

**Comment by umdreamer** [comment]
I encouter the same problem. Do you know how to fix it?

**Comment by umdreamer** [comment]
I finally worked out the problem. Should use the `"mongodb://sorasvl-mongo:27017"`, this works.

**Comment by YuqiHuai** [comment]
Hi @umdreamer 
I apologize for the late reply!

where does it say mongodb://localhost:27017? I need to remove this

**Comment by YuqiHuai** [comment]
I am going to close this issue due to inactivity. Please reopen the issue if the problem isn't solved or open a new one for other issues.

Again, thank you so much for posting issues here!
