### ISSUE TITLE
[feat] python file cannot run

### ISSUE THREAD

**Issue by looles** [YuqiHuai/SORA-SVL#50]
![图片](https://user-images.githubusercontent.com/44311409/232784403-e3f308f5-3f7a-4f3f-a52c-5340a0d7643f.png)

**Comment by looles** [comment]
> Hi @looles I haven't seen this problem before, but it looks like something is missing in your Apollo directory. Can you check which version of Apollo you are using and whether the file described in the error message exists?

hi,我现在可以成功运行示例程序02-apollo-V7程序了，十分感谢，现在遇到一个问题是我安装的是8.0版本的apollo，运行时会遇到下图的问题
![image](https://user-images.githubusercontent.com/44311409/233778228-1c5da2ac-bbcb-497e-aa26-4f5043e72e65.png)
，请问这个连接出现的问题是和apollo的版本有关吗？如果有关，如果要改成8.0的版本，需要更改哪些部分呢？十分感谢您的帮助！

**Comment by YuqiHuai** [comment]
@looles 
您好，我也暂时没跑起来 Apollo 8 + SVL。

**Comment by looles** [comment]
您好，您那边是运行的哪一个版本？6.0吗？

**Comment by YuqiHuai** [comment]
@looles 目前我7.0和8.0都用，我一般用Apollo自带的SimControl不用SVL。

**Comment by YuqiHuai** [comment]
@looles I am going close this issue because it seems to have been resolved. Feel free to reopen it when needed.!
