### ISSUE TITLE
无法运行构建的场景

### ISSUE THREAD

**Issue by CaoYang-1999** [YuqiHuai/SORA-SVL#51]
您好，我按照教程正确的搭建了服务器，但是我不清楚如何将我自己制作的场景进行模拟，
![image](https://user-images.githubusercontent.com/125852708/233273853-0a64677a-171b-4337-a3c8-2428542bfc93.png)

在点击Open Browser按钮后进入了React App页面
![image](https://user-images.githubusercontent.com/125852708/233274081-6185fddb-b006-42c2-aff1-b31bc1d27661.png)

点击API Only按钮
![image](https://user-images.githubusercontent.com/125852708/233274322-cb74d8ad-20bd-469b-a573-3ade11124450.png)

但是此时unity里面并没有跳转场景，而是显示API ready
![image](https://user-images.githubusercontent.com/125852708/233275114-c90588d6-71bc-4641-9a04-27769fb95397.png)

是因为我的development参数没有设置好吗还是因为我的某些步骤不正确呢？
![image](https://user-images.githubusercontent.com/125852708/233275377-4842861c-b9b7-42b6-8c99-3a23a041ffb2.png)

这是我按照教程制作的场景运行时的图片
![image](https://user-images.githubusercontent.com/125852708/233275922-912e6468-d2da-41b5-824e-4080f7d1f278.png)

我替换了D:\UnityProject\SORA-SVL\server\assets\maps下的打包的地图文件，在visual Editor下加载是正确显示的
![image](https://user-images.githubusercontent.com/125852708/233280347-32b5cc99-d9f0-4fda-8850-641b9c872516.png)

在我看的一些教程中，他们会有AddNew操作，是因为我缺少了这一部分操作导致无法正常启动吗
![image](https://user-images.githubusercontent.com/125852708/233281283-73e8ca19-c8ea-4c93-a867-6dbd73c8ad7f.png)

十分感谢！！

**Comment by YuqiHuai** [comment]
Hi @CaoYang-1999 
> 这是我按照教程制作的场景运行时的图片

麻烦您放个教程链接我看看是什么

> 他们会有AddNew操作

以前在SVL的网页服务器里是有AddMap的功能，但是我暂时还没有做进SORA-SVL。因为这个项目是为了暂时保证SVL的正常运行（之前能跑的现在还能跑），还没有投入太多时间添加新功能。如果您做了新的地图想要添加到SORA-SVL里，需要使用 https://github.com/YuqiHuai/SORA-SVL/blob/490b76e5f6452a7f0b9ce37c57f6af7af4ecb597/toolset/map_generator.py 添加到数据库。

**Comment by CaoYang-1999** [comment]
https://www.bilibili.com/video/BV1Wf4y1U741/?spm_id_from=333.999.0.0&vd_source=d44ddd19d0045159ad8db46b5aefb6a5

**Comment by CaoYang-1999** [comment]
这是我看到的教程的链接，操作大概在6:11左右，十分感谢您的回复，明天我就去试一试

**Comment by YuqiHuai** [comment]
@CaoYang-1999 
您好，我大概看了下教程，了解您问题大概在哪。

> 但是此时unity里面并没有跳转场景，而是显示API ready

目前的设计是需要在网页上点击之后SVL进入API Only模式，然后通过LGSVL PythonAPI控制具体加载哪个地图。

> 在我看的一些教程中，他们会有AddNew操作，是因为我缺少了这一部分操作导致无法正常启动吗

是的目前没有做添加地图的UI部分，需要手动通过上面那个Python Script去添加。添加到数据库的主要目的是Python API加载某个Map ID的时候服务器返回相对应的Unity Asset。

**Comment by CaoYang-1999** [comment]
> 

感谢您的回复，在尝试运行Python代码之后，我成功的运行了，十分感谢您的回复！

**Comment by leonzgtee** [comment]
> > 
> 
> 感谢您的回复，在尝试运行Python代码之后，我成功的运行了，十分感谢您的回复！

你好，请问下你自己创建的map可以通过map_generator.py创建成功么

**Comment by CaoYang-1999** [comment]
> > > 
> > 
> > 
> > 感谢您的回复，在尝试运行Python代码之后，我成功的运行了，十分感谢您的回复！
> 
> 你好，请问下你自己创建的map可以通过map_generator.py创建成功么。我使用的时候报错，ZipException，知道是什么原因么。

首先应该从工程中build场景文件，然后再修改map_generator.py里面的代码和build出来的文件信息一致，然后我就创建成功了

**Comment by YuqiHuai** [comment]
@CaoYang-1999 看起来你已经试出来一些使用方法了。我接触SVL比较晚而且目前没有经常在用，你可不可以把你创建成功的过程记录下来然后做个文档。你可以截图并并配一些文字，如果没有时间的话可以发给大概到内容发给我，我把格式做好之后发回给你commit到这个repo。

**Comment by CaoYang-1999** [comment]
> @CaoYang-1999 看起来你已经试出来一些使用方法了。我接触SVL比较晚而且目前没有经常在用，你可不可以把你创建成功的过程记录下来然后做个文档。你可以截图并并配一些文字，如果没有时间的话可以发给大概到内容发给我，我把格式做好之后发回给你commit到这个repo。

您好，我只是运行这个环境成功了，具体过程就是搭建成功环境之后运行工程内的python代码，将代码中的相关信息改为从unity里面打包出来的信息，具体的unity打包的教程可以观看这个链接下的教程：https://www.bilibili.com/video/BV1Wf4y1U741/?spm_id_from=333.1007.top_right_bar_window_custom_collection.content.click&vd_source=d44ddd19d0045159ad8db46b5aefb6a5

**Comment by CaoYang-1999** [comment]
@CaoYang-1999 看起来你已经试出来一些使用方法了。我接触SVL比较晚而且目前没有经常在用，你可不可以把你创建成功的过程记录下来然后做个文档。你可以截图并并配一些文字，如果没有时间的话可以发给大概到内容发给我，我把格式做好之后发回给你commit到这个repo。

您好，我搭建服务器环境是通过您git页面的教程进行的，总结了一下过程：https://www.bilibili.com/read/cv22567733?spm_id_from=333.999.0.0
工程的建立是，搭建成功环境之后通过PyCharm Community Edition运行工程内的python代码，将代码中的相关信息改为从unity里面打包出来的信息，具体的unity打包的教程可以观看这个链接下的教程：https://www.bilibili.com/video/BV1Wf4y1U741/?spm_id_from=333.1007.top_right_bar_window_custom_collection.content.click&vd_source=d44ddd19d0045159ad8db46b5aefb6a5
然后运行unity工程中的LoaderScene场景，到网页上点击开始模拟按钮，可以根据之前build的车辆上的功能进行模拟。
之后的一些功能因为一些原因还没有实现，十分抱歉。

**Comment by CaoYang-1999** [comment]
> @CaoYang-1999 看起来你已经试出来一些使用方法了。我接触SVL比较晚而且目前没有经常在用，你可不可以把你创建成功的过程记录下来然后做个文档。你可以截图并并配一些文字，如果没有时间的话可以发给大概到内容发给我，我把格式做好之后发回给你commit到这个repo。
> 
> 您好，我搭建服务器环境是通过您git页面的教程进行的，总结了一下过程：https://www.bilibili.com/read/cv22567733?spm_id_from=333.999.0.0 工程的建立是，搭建成功环境之后通过PyCharm Community Edition运行工程内的python代码，将代码中的相关信息改为从unity里面打包出来的信息，具体的unity打包的教程可以观看这个链接下的教程：https://www.bilibili.com/video/BV1Wf4y1U741/?spm_id_from=333.1007.top_right_bar_window_custom_collection.content.click&vd_source=d44ddd19d0045159ad8db46b5aefb6a5 然后运行unity工程中的LoaderScene场景，到网页上点击开始模拟按钮，可以根据之前build的车辆上的功能进行模拟。 之后的一些功能因为一些原因还没有实现，十分抱歉。

https://www.bilibili.com/video/BV1bD4y1S75N/?spm_id_from=333.976.top_right_bar_window_custom_collection.content.click
这个是如何build车辆的教程链接

**Comment by YuqiHuai** [comment]
@CaoYang-1999 感谢您的分享 我有时间的时候会去看下这些视频然后加点文档在这里
