### ISSUE TITLE
重启之后如何重新启动本地svl服务器 

### ISSUE THREAD

**Issue by looles** [YuqiHuai/SORA-SVL#53]
![图片](https://user-images.githubusercontent.com/44311409/236465224-eb761e4f-8044-44c2-a224-6e6ced461907.png)
当我关机重启之后，每次都要执行上述脚本才会运行服务器吗？有其他简单的指令吗？我重启之后启动相应的容器是没有效果的。十分感谢

**Comment by YuqiHuai** [comment]
@looles 
> 每次都要执行上述脚本才会运行服务器吗？

是的

> 有其他简单的指令吗？

暂时就是通过这个指令。这个指令同时启动多个container，应该算是已经简化过的。

> 我重启之后启动相应的容器是没有效果的。

麻烦您详细说明一下这个问题

**Comment by looles** [comment]
好的，感谢你的帮助，已了解
