### ISSUE TITLE
Deploy this project and release it for multiple clients to connect and use, replacing the original cloud service.

### ISSUE THREAD

**Issue by noob3-3** [YuqiHuai/SORA-SVL#58]
Thank you for this great project that allows SVL to continue to be used.
The SVL client requires port 8181, but Docker does not expose port 8181. I want to set up a server for my friends to use, so the server and client are not on the same machine. How should this be configured?

**Comment by YuqiHuai** [comment]
Hi, I am pretty sure 8181 is a port opened by the simulator, not Docker/this cloud server. If you want to reconfigure SORA-SVL to run on a different port, you can do so by modifying https://github.com/YuqiHuai/SORA-SVL/blob/681e30f81f352e862ca3c58ec4a7bcff233dcd54/docker-compose.yml#L34

**Comment by Daparrag** [comment]
I have a similar use case did you solve your issue?

**Comment by noob3-3** [comment]
我的问题解决了，我的客户端打开错误了，项目没有问题。我忘了来关闭问题
