### ISSUE TITLE
Loading a Map results in timeout at 0%

### ISSUE THREAD

**Issue by amarkoolk** [YuqiHuai/SORA-SVL#6]
I successfully built and deployed the docker container and the front end seems to be working well. When attempting to use the python api to load Las Vegas Motorspeedway, the simulator attempts to load the map but hangs at 0%

**Comment by YuqiHuai** [comment]
Hi,
Thanks for sending the issue!

Can you share your script so I can take a look? and just to make sure is this the map you are talking about? https://wise.svlsimulator.com/maps/profile/a3be7bf6-b5a6-4e48-833d-a1f1dd6d7a1

**Comment by YuqiHuai** [comment]
I used quickstart/02-loading-scene-show-spawns.py and got the following

Python API Quickstart #2: Loading the scene spawn points
Current Scene = None
Current Scene = a3be7bf6-b5a6-4e48-833d-a1f1dd6d7a1e
Current Scene ID = a3be7bf6-b5a6-4e48-833d-a1f1dd6d7a1e
Spawn(position=Vector(25.1000003814697, 0, -31.2999992370605), rotation=Vector(0, 141.369995117188, 0), destinations=[])
Spawn(position=Vector(0.299999237060547, 0, -0.299999237060547), rotation=Vector(0, 141.369995117188, 0), destinations=[])
Spawn(position=Vector(-26.2000007629395, 0, 32.7999992370605), rotation=Vector(0, 141.369995117188, 0), destinations=[])
Spawn(position=Vector(-47.5, 0, 59.5), rotation=Vector(0, 141.369995117188, 0), destinations=[])

**Comment by amarkoolk** [comment]
`#!/usr/bin/env python3
#
# Copyright (c) 2019-2021 LG Electronics, Inc.
#
# This software contains code licensed as described in LICENSE.
#

from environs import Env
import lgsvl

print("Python API Quickstart #2: Loading the scene spawn points")
env = Env()

sim = lgsvl.Simulator(env.str("LGSVL__SIMULATOR_HOST", lgsvl.wise.SimulatorSettings.simulator_host), env.int("LGSVL__SIMULATOR_PORT", lgsvl.wise.SimulatorSettings.simulator_port))

print("Current Scene = {}".format(sim.current_scene))

# Loads the named map in the connected simulator. The available maps can be set up in web interface
if sim.current_scene == 'a3be7bf6-b5a6-4e48-833d-a1f1dd6d7a1e':
    sim.reset()
else:
    sim.load('a3be7bf6-b5a6-4e48-833d-a1f1dd6d7a1e')

print("Current Scene = {}".format(sim.current_scene))
print("Current Scene ID = {}".format(sim.current_scene_id))

# This will print out the position and rotation vectors for each of the spawn points in the loaded map
spawns = sim.get_spawn()
for spawn in sim.get_spawn():
    print(spawn)
`

I tried using the same quickstart script you did and just replaced the scene with my desired map.

Upon first attempt I get this error message from the Python API.

`Python API Quickstart #2: Loading the scene spawn points
Current Scene = None
Traceback (most recent call last):
  File "02-loading-scene-show-spawns.py", line 22, in <module>
    sim.load('a3be7bf6-b5a6-4e48-833d-a1f1dd6d7a1e')
  File "/home/amar/lgsvlws/src/PythonAPI/lgsvl/utils.py", line 23, in new_f
    return f(*args, **kwargs)
  File "/home/amar/lgsvlws/src/PythonAPI/lgsvl/simulator.py", line 50, in load
    self.remote.command("simulator/load_scene", {"scene": scene, "seed": seed})
  File "/home/amar/lgsvlws/src/PythonAPI/lgsvl/remote.py", line 69, in command
    raise Exception(data["error"])
Exception: Download incomplete, received 0 of 0
`
Upon second attempt, the script hangs here

`Python API Quickstart #2: Loading the scene spawn points
Current Scene = None
`

![image](https://user-images.githubusercontent.com/25155124/174342978-d507f9f1-0f3e-44a8-8d5b-ca763ce9bfec.png)

It remains here for some time, never loading or progressing past 0%.

**Comment by amarkoolk** [comment]
When I use the default borregas avenue, it works perfectly.

**Comment by amarkoolk** [comment]
Ok that helped me figure it out. The preview assets contain the Las Vegas image and name, so it shows up on the server. However there is no actual asset for it in the maps.

**Comment by YuqiHuai** [comment]
Right. I don't have a better optoin to host the asset files for now, so you will have to look for it in the Google Drive folder and manually download it to the desired directory.

Thank you for posting the issue!
