### ISSUE TITLE
[issue] How to change the sensor output topic from svl?

### ISSUE THREAD

**Issue by mgcho0608** [YuqiHuai/SORA-SVL#67]
Hi, I'm using SORA-SVL with Apollo 7.0.0v. I found a serious problem that SORA-SVL sends radar data to /apollo/sensor/conti_radar, while Apollo read radar data from /apollo/sensor/radar/front and /apollo/sensor/radar/rear. As a result of this mismatch, radar is totally unused in perception module. 

I want to fix this issue, and I found from issue tab of Apollo that someone tried to change the topic name of /apollo/sensor/radar/front to /apollo/sensor/conti_radar, but it made difficult error. (https://github.com/ApolloAuto/apollo/issues/14071)

So, I want to change the radar topic of SVL. I use 'grep' to search files including 'conti_radar', and found that mongo/setup/vehicles.json and three dll files in server/assets/plugins include 'conti_radar'.

I changed all 'conti_radar' in vehicles.json, but it didn't change the radar topic of SVL. Now, I'm trying to modify the .dll files in server/assets/plugin. But since .dll files are compiled binary, de-compile + editing + recompile may lead to unintended loss. Any good idea or suggestion for me? Thanks.

**Comment by YuqiHuai** [comment]
Hi @mgcho0608 , thanks for posting an issue!

First, I want to clarify that this isn't a serious problem for SORA-SVL. SORA-SVL isn't sending any radar data, SORA-SVL is just making sure the official SVL client from LG can pull and download necessary assets (e.g., vehicles, maps). I am considering renaming this project to hopefully not cause further misconceptions. 

SVL is responsible for sending radar data, and this local cloud should provide a feature to configure which channel SVL will send data to. However, I did not have enough time to continue developing all the features of this cloud and users have been relying on [this tool](https://github.com/YuqiHuai/SORA-SVL/blob/main/toolset/config_generator.py) to generate new configuration.

I think what you did was on the right track. `vehicles.json` has sensor configurations where you can change what channel a sensor is sending data to. But updating the JSON file changes nothing in the database. You should go into mongodb at `localhost:27018`, find the vehicle configuration you are using, then look at the radar sensor and update output channel in the database.

I believe what I mentioned above should be sufficient to help you send data to the right channel. I am unaware of any `ddl` files and I suggest you stay away from them. In general, I am against modifying anything that came from SVL to maintain its integrity.

**Comment by mgcho0608** [comment]
Thanks, I solved this problem by fixing the mongoDB.
