### ISSUE TITLE
当在bash apollo.sh的时候，出现以下错误，或许您知道是为什么嘛

### ISSUE THREAD

**Issue by lsm2842035890** [YuqiHuai/SORA-SVL#69]
![7ED695E1AAE7758D2C0941EAD7B869DD](https://github.com/YuqiHuai/SORA-SVL/assets/102643200/a0df83f8-1074-4767-8a57-6abc31c6c05c)
使用build_opt_gpu，电脑是有gpu的，nvidia-smi也有相应驱动，为什么用不了？
![91960DA866D7764DC475E7D0864C0490](https://github.com/YuqiHuai/SORA-SVL/assets/102643200/50cfcd9e-866a-4766-8066-e18e20ab04fd)
当使用build_opt_cpu时候，出现几个报错，好像是什么包不存在~您有什么方法嘛

**Comment by YuqiHuai** [comment]
@lsm2842035890 您好，这是一个Apollo问题不是SVL问题。我也不太确定为什么，猜测关于[NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html)。
