### ISSUE TITLE
一直显示正在连接到bridge

### ISSUE THREAD

**Issue by dajiba6** [YuqiHuai/SORA-SVL#74]
![image](https://github.com/YuqiHuai/SORA-SVL/assets/83057203/8f5c8473-5bf6-4492-b295-4a4f2015d1d3)
![image](https://github.com/YuqiHuai/SORA-SVL/assets/83057203/202d91fc-c809-43a3-a681-d3db9c7fc802)

**Comment by ChaoTan201** [comment]
想问一下，现在解决了，怎么解决的，我也遇到这个问题
