### ISSUE TITLE
How to add new sensor configuration ID for vehicles?

### ISSUE THREAD

**Issue by umdreamer** [YuqiHuai/SORA-SVL#8]
Hi @YuqiHuai, I added a new configuation for vehicles in WISE. But I cannot use in the local simulation. I found the ID 6184a957-3630-42b7-974a-d4f6192610d8 is not in the local server: http://localhost/vehicles/2c4aa799-dfd8-4d1a-86de-beff796bd95c (Lexus2016RXHybrid). But I found a lot of other sensor configurations. 

I have searched in the assets/plugins, vechiles directories, but cannot find anything related to the sensor configurations. 

How do you get these existing sensor configurations? And how to add a new sensor configuation for a vehicle? Are they in MongoDB?

Thank you.
![image](https://user-images.githubusercontent.com/15782682/175795358-0c5576f2-784e-4be9-85a8-a02824626d6b.png)

**Comment by JasonBourne1998** [comment]
> Hi @YuqiHuai, I added a new configuation for vehicles in WISE. But I cannot use in the local simulation. I found the ID 6184a957-3630-42b7-974a-d4f6192610d8 is not in the local server: http://localhost/vehicles/2c4aa799-dfd8-4d1a-86de-beff796bd95c (Lexus2016RXHybrid). But I found a lot of other sensor configurations.
> 
> I have searched in the assets/plugins, vechiles directories, but cannot find anything related to the sensor configurations.
> 
> How do you get these existing sensor configurations? And how to add a new sensor configuation for a vehicle? Are they in MongoDB?
> 
> Thank you. ![image](https://user-images.githubusercontent.com/15782682/175795358-0c5576f2-784e-4be9-85a8-a02824626d6b.png)

I guess this version does not have the function. All the sensor configurations are included in the mongo/vehcles.json. I try to edit  
the json file with the configuration page https://wise.svlsimulator.com/api/v1/vehicles/73805704-1e46-4eb6-b5f9-ec2244d5951e. But seems that editing the json file won't help solving the problem. I am not familar with the mongo database, maybe you could have a try on this.

**Comment by umdreamer** [comment]
@JasonBourne1998 Thanks for your reply. I have tried to download json https://wise.svlsimulator.com/api/v1/vehicles/73805704-1e46-4eb6-b5f9-ec2244d5951e. In mongo/vechiles.json, it has two configuration, one is for vechile, the other is for sensor configurations.

For example, http://localhost/api/v1/vehicles/69c7e117-464f-4621-bc1a-2be28af53681
It has senor configuration part:
![image](https://user-images.githubusercontent.com/15782682/175797571-3f7e6058-cf4d-4e89-af1f-56be9b842e05.png)
This configuation can be downloaded from https://wise.svlsimulator.com/vehicles/profile/69c7e117-464f-4621-bc1a-2be28af53681/edit/configuration/64ab7ce0-6f94-42a4-bd0e-ca1e8569c7f0  as Segement Camera.json

This configuration is just a reference, the actual configuation is at the next data. 
They can be downloaded from http://localhost/api/v1/vehicles/64ab7ce0-6f94-42a4-bd0e-ca1e8569c7f0.
The content of this configuation can be get in the  https://wise.svlsimulator.com/vehicles/profile/69c7e117-464f-4621-bc1a-2be28af53681/edit/configuration/b87a56e9-9f56-4279-9521-9601be27c2f1. (in Sensor Details).
![image](https://user-images.githubusercontent.com/15782682/175797728-0ae3691a-6afe-44f5-bffc-f71e5810c787.png)

The problem is that we can not get the json file WISE, just get the interactive interface.

**Comment by umdreamer** [comment]
Here is the sensor configuration in vechiles.json, which can be download from http://localhost/api/v1/vehicles/64ab7ce0-6f94-42a4-bd0e-ca1e8569c7f0, but can not download from https://wise.svlsimulator.com/api/v1/vehicles/64ab7ce0-6f94-42a4-bd0e-ca1e8569c7f0
```
    "_id": {
      "$oid": "6287d8cf7334ff8da9e50a5d"
    },
    "cid": "64ab7ce0-6f94-42a4-bd0e-ca1e8569c7f0",
    "ctype": "configuration",
    "name": "GWMWeyVV72018:GWMWeyVV72018",
    "endpoint": "/api/v1/vehicles/64ab7ce0-6f94-42a4-bd0e-ca1e8569c7f0",
    "data": {
      "assetGuid": "36715078-e872-450c-8c16-64baa36fed20",
      "isShared": false,
      "isFavored": true,
      "isOwned": false,
      "accessInfo": {
        "userAccessType": "favored",
        "owner": {
          "id": "0d888b00-fa53-47c1-882a-b68391268a11",
          "firstName": "SVL",
          "lastName": "Content"
        }
      },
      "supportedSimulatorVersions": [
        "2021.3",
        "2021.2",
        "2021.2.2",
        "2021.1",
        "2021.1.1"
      ],
```

**Comment by JasonBourne1998** [comment]
I get your point. So I guess the best way is to wait the author @YuqiHuai add our sensor configurations into the local wise. I guess he created these json files manually in some way based on the sensor configuration he collected.

**Comment by umdreamer** [comment]
It is not easy to add these json configuration manually. I think it is better to find a way for adding new configurations. Split the big json file into small ones may be a good way. 

Let's wait for the author @YuqiHuai 's solution.

**Comment by YuqiHuai** [comment]
Hi guys! Sorry my bad for not checking issues more frequently!

I mentioned at the other issue that Amar from UVA was able to get custom sensor configuration added. I will work with him and get this feature ASAP.

**Comment by YuqiHuai** [comment]
Regarding this comment https://github.com/YuqiHuai/SORA-SVL/issues/8#issuecomment-1166407427

I actually downloaded it from WISE. You need to add a SimId in the header to retrieve that data. If that header is missing WISE will say Not Found.

**Comment by YuqiHuai** [comment]
Regarding this comment https://github.com/YuqiHuai/SORA-SVL/issues/8#issuecomment-1166401182

yes, changing anything on WISE won’t affect the local cloud. The dataset used by local WISE was collected a few weeks ago, you can think of it as a snapshot of WISE few weeks ago.

**Comment by JasonBourne1998** [comment]
> Hi guys! Sorry my bad for not checking issues more frequently!
> 
> I mentioned at the other issue that Amar from UVA was able to get custom sensor configuration added. I will work with him and get this feature ASAP.

Hi Yuqi. Thanks for your reply and glad to hear that this work is in process. I am just curious that my configuration is public but it still be missed.
![image](https://user-images.githubusercontent.com/51346614/175836139-83492cd0-d6b0-4ead-bcb1-4c9a13bff5c0.png)

**Comment by YuqiHuai** [comment]
Maybe it wasn’t public when I was collecting it? I collected things from wise.svl simulator.com/api/v1/vehicles 
About 3 weeks ago.

**Comment by JasonBourne1998** [comment]
> Maybe it wasn’t public when I was collecting it? I collected things from wise.svl simulator.com/api/v1/vehicles About 3 weeks ago.

Thanks for explanning this, so could you please add @umdreamer's asset **6184a957-3630-42b7-974a-d4f6192610d8** in the **Lexus2016RXHybrid** and my asset **115d0f9c-42f1-4cea-91d1-582e57b74962** in the **Lincoln2017MKZ**? Or we have to wait for the custom sensor configuration in the future?

**Comment by YuqiHuai** [comment]
Sure! I can try to see if I can access them from WISE. I’m not at my workspace at the moment. I’ll keep you guys updated here!

**Comment by YuqiHuai** [comment]
A quick question! Do you guys have any custom sensors in the config?

**Comment by JasonBourne1998** [comment]
> A quick question! Do you guys have any custom sensors in the config?

I don't have any custom sensors and I can open the page in my ipad and mobile phone, so I think it could be collected for others.
![image](https://user-images.githubusercontent.com/51346614/175836599-e094bf8e-1a5a-45cb-8382-f7f58179604e.png)
But it seems that @umdreamer's asset **6184a957-3630-42b7-974a-d4f6192610d8** could not be accessed, maybe he make it private?

**Comment by YuqiHuai** [comment]
Can you download the json file for this? The button is located on the top right of your screenshot.

**Comment by JasonBourne1998** [comment]
Yes, I can download it in the webUI

**Comment by YuqiHuai** [comment]
Can you upload that json file here? And what bridge are you using? Is it cyberRT, ROS, or ROS2?

**Comment by JasonBourne1998** [comment]
The json file: https://drive.google.com/file/d/1q6duUAH0FHdMu6zo8uwKEOCXqhgT9TUB/view?usp=sharing
Bridge: cyberRT

**Comment by YuqiHuai** [comment]
Great! Thanks!

**Comment by JasonBourne1998** [comment]
Thanks！😁

**Comment by YuqiHuai** [comment]
@JasonBourne1998 Hi please take a look at this https://github.com/YuqiHuai/SORA-SVL/blob/master/toolset/config_generator.py

Amar helped building this tool that allows you to add custom sensor config to the database. It won't be displayed on the front end for now but works for the SVL client.

**Comment by JasonBourne1998** [comment]
> @JasonBourne1998 Hi please take a look at this https://github.com/YuqiHuai/SORA-SVL/blob/master/toolset/config_generator.py
> 
> Amar helped building this tool that allows you to add custom sensor config to the database. It won't be displayed on the front end for now but works for the SVL client.

OK, thanks for your work.:)

**Comment by YuqiHuai** [comment]
Hi @JasonBourne1998 ! How was it? Did you manage to add your sensor configuration?

The database isn't persistent each time you restart the entire stack, therefore I haven't added the feature to frontend yet. I used to know how to make data persistent but for some reason, I wasn't able to make it work this time.

**Comment by umdreamer** [comment]
> 

Yes, my cofiguration is private. But I did share it last week. I haven't figure out why it cannot be shared. @JasonBourne1998  Do you know how to share the custom configuration? Thanks.
The configation of 80840dc3-c07a-4689-882c-b3f687d8dff8 (custom configuation) is actually the data part of in the vehicles.json. Where it is missing the "ctype: configuration" part.

**Comment by umdreamer** [comment]
@YuqiHuai I'll try to use the new ones to test the simulation to see if it works. Tommorrow is the last WISE day, we have to make sure everthing goes well.:)

**Comment by JasonBourne1998** [comment]
> Hi @JasonBourne1998 ! How was it? Did you manage to add your sensor configuration?
> 
> The database isn't persistent each time you restart the entire stack, therefore I haven't added the feature to frontend yet. I used to know how to make data persistent but for some reason, I wasn't able to make it work this time.

I have run it successfully, thanks! 
Besides, I have another question about the WEBUI. Do you konw how to get the SVL web' s test report? Since some sensor like stop line sensor didn't build well, it could not get callback on Pythonapi, but could get callback through the test report on WebUI.
Reference issue: https://github.com/lgsvl/simulator/issues/1358

**Comment by JasonBourne1998** [comment]
> > 
> 
> Yes, my cofiguration is private. But I did share it last week. I haven't figure out why it cannot be shared. @JasonBourne1998 Do you know how to share the custom configuration? Thanks. The configation of 80840dc3-c07a-4689-882c-b3f687d8dff8 (custom configuation) is actually the data part of in the vehicles.json. Where it is missing the "ctype: configuration" part.

You could use the toolset/config_generator.py to add your vehicle right now.

**Comment by YuqiHuai** [comment]
@umdreamer Yes, as mentioned above the script will take care of generating appropriate structure, and you just have to provide the sensors array. On WISE there is a download button for vehicle configuration which lets you download the array as a JSON file.

@JasonBourne1998 I did notice a test report endpoint, but I wasn't able to get the client send anything to that end point. I can spend some time trying to figure this out but this will probably not come anytime soon.

**Comment by JasonBourne1998** [comment]
> @umdreamer Yes, as mentioned above the script will take care of generating appropriate structure, and you just have to provide the sensors array. On WISE there is a download button for vehicle configuration which lets you download the array as a JSON file. I added "cypte:configuration" to distinguish data. For vehicles there are IDs referring to the vehicle (parent of all sensor configurations), then there are IDs individual sensor configurations. Maybe we should clean or restructure the database in the future, but for now it does the job.
> 
> @JasonBourne1998 I did notice a test report endpoint, but I wasn't able to get the client send anything to that end point. I can spend some time trying to figure this out but this will probably not come anytime soon. Sorry about that!

Sounds good, thanks for your excellent work:)

**Comment by YuqiHuai** [comment]
I was able to make the database persistent in one of the recent commits and I plan to add this feature over the weekend.

**Comment by umdreamer** [comment]
> @JasonBourne1998 Hi please take a look at this https://github.com/YuqiHuai/SORA-SVL/blob/master/toolset/config_generator.py
> 
> Amar helped building this tool that allows you to add custom sensor config to the database. It won't be displayed on the front end for now but works for the SVL client.

Hi @JasonBourne1998 , how to you manage to get the script work? Did you run from container sorasvl-server or sorasvl-mongo?

**Comment by umdreamer** [comment]
OK, I found it.
In windows, just modify the code  to connect to mongodb.
`self.client = pymongo.MongoClient('mongodb://localhost:28018')`
This can connect mongodb from localhost through port 28018 (which is mapped to 27017 in container).

Then we can run the python file. 
Cheers.

**Comment by YuqiHuai** [comment]
Sorry for not responding to this earlier. You figured out things correctly, and I added this change to the script.

The script is intended to run outside of the containers.

**Comment by YuqiHuai** [comment]
@umdreamer Thank you for your contribution. Since your PR has been merged, is it safe to close this issue?

**Comment by umdreamer** [comment]
Yes, I close it.
