### ISSUE TITLE
fail to run "docker compose up --build -d"

### ISSUE THREAD

**Issue by AOOOOOA** [YuqiHuai/SORA-SVL#82]
**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version of SVL 2021.03
 - Docker version:  24.0.2

Hi, thanks for your excellent work!

When I try to run the "docker compose up --build -d", it fails with the report :

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x39 pc=0x102c629]

goroutine 11 [running]:
github.com/docker/buildx/builder.(*Builder).Validate(0x22e1780?)
	github.com/docker/buildx@v0.10.4/builder/builder.go:111 +0x29
github.com/docker/buildx/builder.New({0x22e1780?, 0xc0000e2600}, {0x0, 0x0, 0x0?})
	github.com/docker/buildx@v0.10.4/builder/builder.go:101 +0x27f
github.com/docker/compose/v2/pkg/compose.(*composeService).doBuildBuildkit(_, {_, _}, {_, _}, {{{0xc0006a7da0, 0x26}, {0xc000062800, 0x31}, {0x0, ...}, ...}, ...}, ...)
	github.com/docker/compose/v2/pkg/compose/build_buildkit.go:39 +0x72
github.com/docker/compose/v2/pkg/compose.(*composeService).build.func1({0x22d0620, 0xc000386230}, {0xc00005bea0, 0x5})
	github.com/docker/compose/v2/pkg/compose/build.go:115 +0x6fe
github.com/docker/compose/v2/pkg/compose.(*graphTraversal).run.func1()
	github.com/docker/compose/v2/pkg/compose/dependencies.go:145 +0x59
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.2.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.2.0/errgroup/errgroup.go:72 +0xa5

Have you ever seen this? Could you please help me with it? Thanks!! @YuqiHuai

**Comment by AOOOOOA** [comment]
I have changed the version of my docker but the issue still exist...

**Comment by YuqiHuai** [comment]
@AOOOOOA Sorry not sure how I missed this issue. This really looks like docker is not installed properly and I have not seen this before.

**Comment by YuqiHuai** [comment]
Looks like this has became a common issue and many of you have managed to solve it.
