### ISSUE TITLE
[feat] docker compose up --build -d

### ISSUE THREAD

**Issue by tuoerning** [YuqiHuai/SORA-SVL#84]
![截图 2024-07-19 19-35-06](https://github.com/user-attachments/assets/19baf6da-52c7-463d-b913-9c165b6fd7b3)
I encountered this problem when using docker, is there any solution

**Comment by YuqiHuai** [comment]
Looks like it is not pulling the docker container from the docker hub properly. Not sure if this is related to if you are running this in China.

**Comment by CarrotZelda** [comment]
我也遇到了这个问题，只需要更改一下docker的镜像就好了。
运行`sudo vi /etc/docker/daemon.json`，然后在daemon.json中添加以下内容后保存。
`{
 
"registry-mirrors": [
 
"https://docker.m.daocloud.io",
 
"https://docker.nju.edu.cn",
 
"https://dockerproxy.com"
 
]
 
}`

最后重启docker：`sudo systemctl restart docker`。
此时就可以执行`docker compose up --build -d`了。 @tuoerning

**Comment by YuqiHuai** [comment]
@CarrotZelda Thank you for your input!

**Comment by CarrotZelda** [comment]
不需要

**Comment by Yuppie6** [comment]
@CarrotZelda 您好。按照您的方法进行修改过后还是出现了同样的问题。我在别处看到的解决方法是加入阿里云的镜像，我想知道多个镜像是否会产生冲突。

**Comment by CarrotZelda** [comment]
我猜是那几个镜像链接失效了，我之前添加了好几个镜像没有冲突。你也可以试试把那几个去掉，加阿里云的镜像。

**Comment by Yuppie6** [comment]
我在此之前是单独添加了阿里云的镜像 但也是同样的问题。出现这个问题归根到底的原因就是因为镜像吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月03日 21:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [YuqiHuai/SORA-SVL] [feat] docker compose up --build -d (Issue #84) |

我猜是那几个镜像链接失效了，我之前添加了好几个镜像没有冲突。你也可以试试把那几个去掉，加阿里云的镜像。

**Comment by CarrotZelda** [comment]
我也不清楚根本原因是什么，但是换镜像链接确实能够build成功，我昨晚在新环境上配了一下，添加了一些新的链接。build的过程很慢，但最终没有报错，build成功了。下面是我的daemon.json内的镜像内容。

"registry-mirrors": [
"https://docker.1panel.dev",
"https://docker.fxxk.dedyn.io",
"https://docker.xn--6oq72ry9d5zx.cn",
"https://docker.m.daocloud.io",
"https://a.ussh.net",
"https://docker.zhai.cm",
"https://docker.nju.edu.cn",
"https://dockerproxy.com",
"http://docker.1panel.live",
"https://dockerpull.com",
"https://docker.1panel.live",
"https://dockerproxy.cn",
"https://docker.hpcloud.cloud"],

**Comment by CarrotZelda** [comment]
还有一件事，我参考了issue89，https://github.com/YuqiHuai/SORA-SVL/issues/89#issuecomment-2370252260，把client文件夹与server文件夹中的Dockerfile做了些修改，在RUN npm install上面加了一行RUN npm config set registry https://registry.npmmirror.com

**Comment by 5945hmc** [comment]
@CarrotZelda   Hello! As you said in the client and server dockerfile increased RUN NPM install, registry=https://registry.npmmirror.com, but still an error
![f65f8488e5a4f3c4db624e184a4ca7c](https://github.com/user-attachments/assets/98c9c25c-ea5a-48ee-84c6-eea47b27ae18)
![bd3573f8398948f647807c3997d5310](https://github.com/user-attachments/assets/cea8baa2-2c5a-454f-80f2-19df1cd6e8e4)

**Comment by 5945hmc** [comment]
@CarrotZelda     @AHPUymhd  @YuqiHuai   您好！  我在运行 docker compose up --build -d  遇到以下问题  请问您们遇到了吗 请分享下解决方法  谢谢！
![Uploading 88f26be6599b5b32f3bb8bb0efca2a4.jpg…]()

**Comment by YuqiHuai** [comment]
@5945hmc 抱歉我没自己解决过这个问题 目前看起来都是在国内是不是npm镜像源被墙了 我觉得您找个国内的npm镜像源应该能解决问题

**Comment by 5945hmc** [comment]
&nbsp; &nbsp; &nbsp;您好！
&nbsp; &nbsp; &nbsp; 请问下 lgsvl与apollo7.0 进行联合仿真（bridgel连接成功了），LGSVL中加载SanFrancisco 地图，apollo/modules/map/data 下新建了这个地图信息base_map.bin、routing_map.bin、sim_map.bin，两者联合仿真时 Dreamview 中 车辆定个位不准确，请问这是咋回事 ？&nbsp;













xm
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuqiHuai/SORA-SVL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年1月3日(星期五) 中午12:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuqiHuai/SORA-SVL] [feat] docker compose up --build -d (Issue #84)





 
@5945hmc 抱歉我没自己解决过这个问题 目前看起来都是在国内是不是npm镜像源被墙了 我觉得您找个国内的npm镜像源应该能解决问题

**Comment by YuqiHuai** [comment]
@5945hmc SanFrancisco这个地图有点问题 有个叫SanFrancisco_Correct或者Correct2之类的地图 要用那个

**Comment by 5945hmc** [comment]
您好！您可以把SanFrancisco_Correct和Correct2的地图&nbsp; base-map. bin文件分享一下给我吗？(我好像没找到)&nbsp; 非常感谢您！










xm
***@***.***






---Original---
From: "Yuqi ***@***.***&gt;
Date: Fri, Jan 3, 2025 12:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [YuqiHuai/SORA-SVL] [feat] docker compose up --build -d (Issue#84)




 
@5945hmc SanFrancisco这个地图有点问题 有个叫SanFrancisco_Correct或者Correct2之类的地图 要用那个

**Comment by YuqiHuai** [comment]
@5945hmc 都在这个项目的readme里那个GoogleDrive/百度网盘里 您得看一下哪个id对应的这个

**Comment by 5945hmc** [comment]
好的，谢谢












xm
***@***.***






---Original---
From: "Yuqi ***@***.***&gt;
Date: Fri, Jan 3, 2025 13:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [YuqiHuai/SORA-SVL] [feat] docker compose up --build -d (Issue#84)




 
@5945hmc 都在这个项目的readme里那个GoogleDrive/百度网盘里 您得看一下哪个id对应的这个
