### ISSUE TITLE
Apollo 9.0 + SORA-SVL co-simulation availability

### ISSUE THREAD

**Issue by Kim-mins** [YuqiHuai/SORA-SVL#86]
Hi, I'm currently trying to run Apollo with SORA-SVL(Thank you for the nice work!), 
and **I wonder if it is possible to run co-simulation on SORA-SVL with the latest Apollo, Apollo 9.0 or Apollo 8.0.**

It seems SORA-SVL supports co-simulation with Apollo 7.0, but I could get no hint on the versions above.

Thank you in advance!

**Comment by YuqiHuai** [comment]
Hi! Thanks for reaching out. From memory I could not get SVL to work properly with Apollo 8.0, I assume tit would also not work with Apollo 9.0.

**Comment by Kim-mins** [comment]
Thank you for the quick response @YuqiHuai!

Seems I should investigate the co-simulation with Carla.. Thanks!
