### ISSUE TITLE
【server 5/7】RUN npm install

### ISSUE THREAD

**Issue by lsm2842035890** [YuqiHuai/SORA-SVL#89]
执行完docker compose up --build -d之后，构建到[server 5/7]RUN npm install的时候为什么这么慢，十几分钟还没结束，是镜像的原因吗，已经换成国内镜像了~

**Comment by lsm2842035890** [comment]
解决了

**Comment by YuqiHuai** [comment]
@lsm2842035890 抱歉 是更换镜像后解决的吗？

**Comment by lsm2842035890** [comment]
是的，在这里指定国内的源编译很快,用默认官方的源在国内巨慢
FROM node:18
RUN mkdir /workdir
ADD package.json /workdir

WORKDIR /workdir

RUN npm install **--registry=https://gegistry.npmmirror.com**
ADD ./ /workdir

EXPOSE 3000
RUN ["npm", "run", "build"]
CMD [ "npm", "run", "start" ]

**Comment by YuqiHuai** [comment]
好的 我迟点把这个信息弄得明显一点 感谢分享

**Comment by 5945hmc** [comment]
@lsm2842035890      Hello! As you said in the client and server dockerfile increased RUN NPM install, registry=https://registry.npmmirror.com, but still an error  
![f65f8488e5a4f3c4db624e184a4ca7c](https://github.com/user-attachments/assets/7cb7999c-019c-4c48-87e0-06f970655fc9)
![Uploading bd3573f8398948f647807c3997d5310.jpg…]()

**Comment by 5945hmc** [comment]
@YuqiHuai   Hello! As you said in the client and server dockerfile increased RUN NPM install, registry=https://registry.npmmirror.com, but still an error
![bd3573f8398948f647807c3997d5310](https://github.com/user-attachments/assets/97eba4b6-4afb-4edb-9aa0-dbf5ac579fa6)

**Comment by lxxvjk** [comment]
你好，我换了阿里云的镜像之后还是一直在进行，没有停止。请问是什么问题？

![image](https://github.com/user-attachments/assets/c3fdb119-3ba3-4894-927e-f7112e0a0d0d)
