### ISSUE TITLE
车辆SignalSensor的Topic修改

### ISSUE THREAD

**Issue by Utopiaaaaaaaaa** [YuqiHuai/SORA-SVL#90]
我希望修改SignalSensor传感器的Topic，使红绿灯信息不直接输出到/apollo/perception/traffic_light，而是输出到自定义的某个Channel中，请问这在SORA中可以实现么？我尝试修改了SORA-SVL/mongo/setup中车辆的json文件，但似乎并没有作用

**Comment by YuqiHuai** [comment]
您有没有看这个Issue https://github.com/YuqiHuai/SORA-SVL/issues/67
我也试着自己操作一下看看

**Comment by YuqiHuai** [comment]
https://github.com/YuqiHuai/SORA-SVL/blob/main/toolset/change_sensor_topic.py
![image](https://github.com/user-attachments/assets/35478d17-29b9-422e-89dd-aa1e9f7d8d22)

在我这里测试了一下应该没问题,您可以试试看,这个功能好像不太难做成网页,等我之后有时间做一下

**Comment by Utopiaaaaaaaaa** [comment]
感谢您的帮助，我成功修改了传感器的Topic
